name: 'Install Linux Prerequisites'
description: 'Installs system dependencies for AppFlowy on Linux'
runs:
  using: "composite"
  steps:
    - name: Install prerequisites
      shell: bash
      run: |
        sudo wget -qO /etc/apt/trusted.gpg.d/dart_linux_signing_key.asc https://dl-ssl.google.com/linux/linux_signing_key.pub
        sudo wget -qO /etc/apt/sources.list.d/dart_stable.list https://storage.googleapis.com/download.dartlang.org/linux/debian/dart_stable.list
        sudo apt-get update
        sudo apt-get install -y dart curl build-essential libssl-dev clang cmake ninja-build pkg-config libgtk-3-dev keybinder-3.0 libnotify-dev network-manager libcurl4-openssl-dev libmpv-dev mpv libasound2-dev unzip
        # Install GStreamer for audioplayers_linux
        # Install libunwind-dev first to resolve dependency issues
        sudo apt-get -y install libunwind-dev
        sudo apt-get -y install libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev
